"""Add auth fields to User model

Revision ID: 48356d6f268e
Revises: b81614f68712
Create Date: 2026-02-18 17:26:01.938288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48356d6f268e'
down_revision = 'b81614f68712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reset_token_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token_hash')
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
